apiVersion: v1
kind: Service
metadata:
  name: iptv-proxy
  labels:
    app: iptv-proxy
spec:
  type: NodePort
  selector:
    app: iptv-proxy
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
